# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          version="hello" 
          echo "VERSION=$version" >> $GITHUB_ENV    

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "${{ env.VERSION }}"
